### ISSUE TITLE
Any documentation or guide about how to use it?

### ISSUE THREAD

**Issue by rocandante** [anomalylabs/comments-module#3]
Hi, I installed the comments module to test it and in the admin it appears correctly but I can not find documentation on how to insert the form on any page or how to use it. Can someone guide me?

**Comment by rocandante** [comment]
Looking at the code can deduce the way to get the comments and the submission form.
List user's comments
{{ comments(page()) }}
and show comment form
{{ form('comment').subject(page())|raw }}

However, it is unclear to me how the mentions are made and what other features are included. I also have problems in the admin to edit a comment, 500 error occurs, just as if I try to approve a comment. It seems like something is missing. I appreciate any help to make it work properly. Thanks

**Comment by RyanThompson** [comment]
This is still under development - I'll post / blast about it when I finish. Shouldn't be too long just have some priorities before it.
